#!/usr/bin/env node

let fs = require('fs')
let {program} = require('commander')
let pkg = require('./package.json')
let lib = require('./lib')

program
    .version(pkg.version)
    .description(pkg.description)
    .option('-l <str>', "a 2-letter default language, if <html lang='xx'> attribute is absent; this does NOT override already present lang= attributes")
    .option('-i <str>', 'a comma-separated list of tags to ignore')
    .option('--lang-list', 'list all supported languages')
program.parse()

if (program.opts().langList) {
    console.log(Object.keys(pkg.dependencies)
                .filter( v => /^hyphenation\./.test(v))
                .map( v => v.replace(/^hyphenation\./, '')).join`\n`)
    process.exit()
}

read(program.args[0]).then( xml => {
    return lib.hyphenate(xml, program.opts())
}).then( str => {
    process.stdout.write(str)
}).catch( err => {
    console.error(err.message)
    process.exitCode = 1
})

function read(file) {
    let stream = file ? fs.createReadStream(file) : process.stdin
    let data = []
    return new Promise( (resolve, reject) => {
        stream.on('error', reject)
        stream.on('data', chunk => data.push(chunk))
        stream.on('end', () => resolve({
            filename: file || '[stdin]',
            text: Buffer.concat(data).toString()
        }))
    })
}
